export const GET_CURRENT_DRINKS_LIST = 'GET_CURRENT_DRINKS_LIST';
export const UPDATE_CURRENT_DRINKS_LIST = 'UPDATE_CURRENT_DRINKS_LIST';

export const GET_SEARCH_LIST = 'GET_SEARCH_LIST';
export const SET_SEARCH_LIST = 'SET_SEARCH_LIST';

export const GET_GIN_DRINKS = 'GET_GIN_DRINKS';
export const GET_RUM_DRINKS = 'GET_RUM_DRINKS';
export const GET_TEQUILA_DRINKS = 'GET_TEQUILA_DRINKS';
export const GET_VODKA_DRINKS = 'GET_VODKA_DRINKS';
export const GET_DRINKS_ERROR = 'GET_DRINKS_ERROR';

export const SET_SELECTED_DRINK = 'SET_SELECTED_DRINK';
export const SET_SELECTED_DRINK_ERROR = 'SET_SELECTED_DRINK_ERROR';

export const SET_LOADING = 'SET_LOADING';
export const SET_SELECTED_TAB = 'SET_SELECTED_TAB';

export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const UPDATE_CURRENT_USER_ERROR = 'UPDATE_CURRENT_USER_ERROR';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
